version: '3.9'

# Port mappings:
# 11000: Nextcloud
# 8080: Nextcloud AIO Admin-Panel
# 8081: Etherpad
# 8082: Kutt
# 8083: Reposilite

services:
  # ==================== Nextcloud ====================
  nextcloud_aio_mastercontainer:
    image: nextcloud/all-in-one:latest #-arm64
    restart: always
    container_name: "nextcloud-aio-mastercontainer"
    ports:
      - "8080:8080"
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=127.0.0.1
      # - NEXTCLOUD_UPLOAD_LIMIT=10G
      # - NEXTCLOUD_MAX_TIME=3600

  # ==================== Etherpad ====================
  etherpad:
    image: etherpad/etherpad:latest # Use etherpad:develop on arm64
    restart: always
    container_name: "etherpad"
    ports:
      - "8081:9001"
    depends_on:
      - etherpad_db
    environment:
      TRUST_PROXY: true
      ADMIN_PASSWORD: CHANGEME_PAD_ADMIN # Password for the "admin"-user here
      DB_TYPE: postgres
      DB_HOST: etherpad_db
      DB_PORT: 5432
      DB_NAME: etherpad
      DB_USER: postgres
      DB_PASS: CHANGEME_PAD_DB # Etherpad DB password here

  etherpad_db:
    image: postgres:alpine
    restart: always
    container_name: "etherpad_db"
    environment:
      POSTGRES_DB: etherpad
      POSTGRES_PASSWORD: CHANGEME_PAD_DB # Etherpad DB password here
    volumes:
      - etherpad_db:/var/lib/postgresql/data

  # ==================== Kutt ====================
  kutt:
    image: kutt/kutt:latest
    restart: always
    container_name: "kutt"
    depends_on:
      - kutt_redis
      - kutt_db
    command: ["./wait-for-it.sh", "kutt_db:5432", "--", "npm", "start"]
    ports:
      - "8082:3000"
    environment:
      DEFAULT_DOMAIN: link.example.com # Kutt domain here
      SITE_NAME: Kutt

      LINK_LENGTH: 6
      DISALLOW_REGISTRATION: false
      DISALLOW_ANONYMOUS_LINKS: false
      USER_LIMIT_PER_DAY: 50
      NON_USER_COOLDOWN: 0
      DEFAULT_MAX_STATS_PER_LINK: 5000
      CUSTOM_DOMAIN_USE_HTTPS: false

      DB_HOST: kutt_db
      DB_PORT: 5432
      DB_NAME: kutt
      DB_USER: postgres
      DB_PASSWORD: CHANGEME_KUTT_DB # Kutt DB password here
      REDIS_HOST: kutt_redis
      REDIS_PORT: 6379

      # Comma-seperated list of admin accounts
      ADMIN_EMAILS: example@example.com
      # Email to send link reports to
      REPORT_EMAIL: example@example.com
      # Email to send the account verification emails from
      MAIL_HOST: mail.example.com
      MAIL_PORT: 587
      MAIL_SECURE: true
      MAIL_USER: example@example.com
      MAIL_PASSWORD: "password"

      # A passphrase to encrypt JWT. Use a long and secure key.
      JWT_SECRET: "securekey"

  kutt_db:
    image: postgres:alpine
    restart: always
    container_name: "kutt_db"
    environment:
      POSTGRES_DB: kutt
      POSTGRES_PASSWORD: CHANGEME_KUTT_DB # Kutt DB password here
    volumes:
      - kutt_db:/var/lib/postgresql/data

  kutt_redis:
    image: redis:alpine
    restart: always
    container_name: "kutt_redis"
    volumes:
      - kutt_redis:/data

  # ==================== Reposilite ====================
  # Needs custom setup: https://reposilite.com/guide/docker#using-docker-compose
  reposilite:
    image: dzikoysk/reposilite:3.1.0
    restart: always
    container_name: "reposilite"
    volumes:
      - reposilite_data:/app/data
    ports:
      - "8083:8080"
    environment:
      - JAVA_OPTS=-Xmx128M
      - REPOSILITE_OPTS=--token temp:CHANGEME_REPO_TOKEN # Password for the "temp" setup-user here

  # ==================== Caddy ====================
  caddy:
    image: caddy:latest
    restart: always
    container_name: "caddy"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_config:/config
      - caddy_data:/data
    network_mode: host

volumes:
  nextcloud_aio_mastercontainer:
    name: "nextcloud_aio_mastercontainer"
  etherpad_db:
    name: "etherpad_db"
  kutt_redis:
    name: "kutt_redis"
  kutt_db:
    name: "kutt_db"
  reposilite_data:
    name: "reposilite_data"
  caddy_data:
    name: "caddy_data"
  caddy_config:
    name: "caddy_config"
