version: '3'

# Used ports: (8083: HTTP)

services:
    # Needs custom setup: https://reposilite.com/guide/docker#using-docker-compose
    reposilite:
        image: dzikoysk/reposilite:latest
        container_name: 'reposilite'
        restart: unless-stopped
        ports:
            - 8083:8080
        volumes:
            - reposilite_data:/app/data
        environment:
            - JAVA_OPTS=-Xmx128M
            - REPOSILITE_OPTS=--token temp:temp

volumes:
    reposilite_data:
        name: 'reposilite_data'
