version: '3'

# Ports: (8081/External 8080/Internal: HTTP)

services:
    # Generate the first account by attaching to the container: https://reposilite.com/guide/tokens#generating-token
    reposilite:
        image: dzikoysk/reposilite:latest
        container_name: 'reposilite'
        restart: unless-stopped
        stdin_open: true
        tty: true
        ports:
            - 8081:8080
        volumes:
            - reposilite_data:/app/data
        environment:
            - JAVA_OPTS=-Xmx128M

volumes:
    reposilite_data:
        name: 'reposilite_data'
